# CONFIGURACION DEL SERVIDOR
spring.application.name=todolist-api
server.port=${PORT:8080}
server.servlet.context-path=/api

# CONFIGURACION DE LA BASE DE DATOS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION DE HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# POOL DE CONEXIONES
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5